# config/account.yaml
# 恋愛・人間関係アカウントの設定

genre: 'renai'
locale: 'ja-JP'
posting:
  time_window: ['09:00', '11:00']
  days: [Mon, Tue, Wed, Thu, Fri]
ai:
  provider: 'openrouter'
  # ーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーー
  # ーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーー
  # ↓から無料のAPIを探す
  # https://openrouter.ai/models?max_price=0
  # ーーーーーーーーーーーーーーーーーーーーーー

  # ↓早いし、内容も問題なさそう
  # 2025/06/25 なぜか認証エラーで使えなくなった
  # const MODEL = 'meta-llama/llama-4-maverick:free';

  # ↓少し遅いがまあまあ文章作成能力も高そう
  # const MODEL = 'deepseek/deepseek-chat-v3-0324:free';

  # ↓記事は作れるが、ちょっとクオリティが低いかも（ランキング2位までしか作れない）
  # export const MODEL = 'x-ai/grok-4-fast:free'

  # ↓記事のクオリティが良く、使える
  # const MODEL = 'deepseek/deepseek-chat-v3.1:free'

  # ----すべて同じmodelを指定する場合→model-------------------------------------
  # const MODEL = 'google/gemini-pro'; // 必要に応じて変更
  # const MODEL = 'google/gemini-2.5-pro-exp-03-25';

  # const MODEL = 'google/gemini-2.0-flash-exp:free';

  model: 'x-ai/grok-4-fast:free'

  # ----記事作成・リライト・タグ生成それぞれで別のmodelを指定する場合→models-----
  # 新しい個別モデル指定
  models:
    article: 'x-ai/grok-4-fast:free'    # 記事作成用
    rewrite: 'x-ai/grok-4-fast:free'       # リライト用
    tags: 'x-ai/grok-4-fast:free'          # タグ生成用
  # ーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーー
  temperature: 0.7
  max_tokens: 1200
note:
  login_method: 'email_password'
  cookie_secret_name: 'NOTE_COOKIE'
sheets:
  enabled: true
  doc_id: ''
  worksheet: 'posts'
overrides:
  seasonal_topic: '恋愛・人間関係'
  tags:
    [
      '#人間関係',
      '#メンタル',
      '#自己肯定感',
      '#引き寄せ',
      '#引き寄せの法則',
      '#裏技',
      '#PR',
    ]
